# Generated by Django 5.2.1 on 2025-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
