# Generated by Django 5.2.1 on 2025-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariant_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_color',
            field=models.ManyToManyField(to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_size',
            field=models.ManyToManyField(to='products.sizevariant'),
        ),
    ]
