# Generated by Django 5.2.1 on 2025-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_products_color_products_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_color',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_size',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
    ]
