# Generated by Django 5.2.1 on 2025-05-21 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_products_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('discount_price', models.IntegerField()),
                ('is_expired', models.BooleanField(default=False)),
                ('min_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
